feat: git pull

diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -1,4 +1,9 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-exec </dev/tty && node_modules/.bin/cz --hook || true
+if [ -x ./node_modules/.bin/cz ]; then
+  exec </dev/tty && ./node_modules/.bin/cz || true
+else
+  echo "❌ Commitizen (cz) not found. Please run: npm install"
+  exit 1
+fi
